### ISSUE TITLE
Beware of String.escape

### ISSUE THREAD

**Issue by dbuenzli** [mirage/mirage-fs#3]
`crunch.ml` uses `String.escape` to write the binary content of a string to an OCaml constant. One should note that `String.escape` writes latin1 characters as is so you really have to make sure the resulting text files are never converted to another encoding.

I just lost time with similar code on my side because I was caught by a spurious UTF-8 translation made by my editor --- I embedded the file with the constant in another one that had UTF-8 characters via `M-x insert-file` so the inserted constant was translated to UTF-8 thus breaking the binary sequence. 

On my side I now prefer to stick to a more robust US-ASCII encoding with something like:

``` ocaml
Printf.printf "\"";
for i = 0 to String.length s - 1 do 
  Printf.printf "\\x%02X" (Char.code s.[i])
done;
Printf.printf "\""
```

**Comment by cfcs** [comment]
@dbuenzli using decimal encoding (`Printf.printf "\\%d" (Char.code s.[i])`) would use fewer characters (2-4 bytes) than hex-encoding (fixed 4 bytes).

**Comment by dbuenzli** [comment]
> @dbuenzli using decimal encoding (Printf.printf "\\%d" (Char.code s.[i])) would use fewer characters (2-4 bytes) than hex-encoding (fixed 4 bytes).

No. Decimal escapes must be made of three digits, so it's four bytes in both cases. Given that I personally find hex more readable (besides it may compress better but I'm not sure about that).

**Comment by cfcs** [comment]
@dbuenzli ah, I stand corrected!

Well in any case I managed to bump this four year old bug report, so here's to hoping someone will see it.
If not I'll be back with another useless reply in 2021. Enjoy your sunday night!
